export enum ConversationStepsEnum {
    START = 'START',
    SETTINGS = 'SETTINGS',
    LANGUAGE_SELECTION = 'LANGUAGE_SELECTION',
    ASKING_PHONE = 'ASKING_PHONE',
    VALIDATION_PHONE = 'VALIDATION_PHONE',
    PHONE_VERIFICATION = 'PHONE_VERIFICATION',
    MAIN_MENU = 'MAIN_MENU',
    PURCHASES = 'PURCHASES',
    CREATING_ORDERS = 'CREATING_PURCHASES',
    CONFIRMED_ORDERS = 'CONFIRMED_PURCHASES',
    COMPLETED_ORDERS = 'COMPLETED_PURCHASES',
    IN_TRANSIT_ORDERS = 'IN_TRANSIT_PURCHASES',
    PENDING_ORDERS = 'PENDING_PURCHASES',
    PAYMENTS = 'PAYMENTS',
    COMPLETED = 'COMPLETED'
}